<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Hero', 'accountra' ),
	'categories' => array( 'accountra-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"890"},"gap":"no","elementId":"guten-P6sVWZ","background":{"type":"default","image":{"Desktop":{"id":75,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/african-american-afro-american-analyzing-black-people-brainstorming-1434697-pxhere.com_.webp"}},"color":"","size":{"Desktop":"cover","Tablet":"cover","Mobile":"cover"},"position":{"Desktop":"custom","Tablet":"center center","Mobile":"bottom left"},"xposition":{"Desktop":{"point":"","unit":"px"}},"yposition":{"Desktop":{"point":"45","unit":"px"}},"repeat":{"Tablet":"no-repeat"},"videoPlayOnMobile":false,"fetchPriorityHigh":true},"backgroundOverlay":{"type":"default","color":{"r":26,"g":20,"b":20,"a":1},"gradientColor":[{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":3,"offset":"0.000"},{"color":"rgba(255, 255, 255, 0)","id":7,"offset":"0.107","active":false},{"color":"rgba(255, 255, 255, 0)","active":true,"id":6,"offset":"0.190"},{"color":"rgba(255, 255, 255, 0)","active":false,"id":5,"offset":"0.293"},{"color":"rgba(255, 255, 255, 0)","active":false,"id":4,"offset":"0.937"}],"gradientType":"linear","gradientAngle":270,"image":{"Desktop":[]}},"opacity":"0.8","margin":{"Desktop":{"unit":"px","dimension":{"top":"-180","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"400","bottom":"270"}},"Tablet":{"unit":"px","dimension":{"top":"380","bottom":"120","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"bottom":"120","top":"360"}}},"zIndex":{"Desktop":"1"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Mobile":null,"Tablet":null},"elementId":"guten-91Fk0O","horizontalAlign":{"Desktop":"center"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-cad3Cf","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-CPw075","horizontalAlign":{"Desktop":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-XvGz0E","content":"Focus On Growing Your Business Trust The \u003cmark style=\u0022background-color:#ffffff00;color:#fcb900\u0022 class=\u0022has-inline-color\u0022\u003eAccounting\u003c/mark\u003e To Us","type":1,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"third"},"typography":{"type":"variable","id":"h1-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"52"},"Tablet":{"unit":"px","point":"42"},"Mobile":{"unit":"px","point":"32"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"500"},"containsAnchorTag":false,"background":{"type":"default"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":"","top":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"","left":"","top":"","bottom":""}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-0iCbAc","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"third"},"typography":{"type":"variable","id":"body-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"right":"","top":"","bottom":"20","left":""}},"Mobile":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"bottom":"15"}}},"padding":{"Desktop":{"unit":"%","dimension":{"right":"18","left":"18","top":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"10","bottom":"0","left":"10"}},"Tablet":{"unit":"%","dimension":{"top":"0","right":"11","bottom":"0","left":"11"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-y7Tk4t","verticalAlign":"center","margin":{"Desktop":{"unit":"px","dimension":{"top":"5"}},"Mobile":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-KNvoZB","horizontalAlign":{"Desktop":"default","Mobile":"default"},"margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<!-- wp:gutenverse/button {"elementId":"guten-BTgZlT","content":"Get A Quote","url":"#","alignButton":{"Desktop":"right","Mobile":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"20","right":"25","bottom":"20","left":"25"}}},"buttonBackground":{"type":"default","color":{"type":"variable","id":"secondary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"third"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"40"},"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"button1-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":"uppercase","weight":"500","transform":"uppercase"},"hoverTextColor":{"type":"variable","id":"primary"},"ariaLabel":"get started"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Mobile":100},"sectionVerticalAlign":"center","elementId":"guten-MidhJF","verticalAlign":{"Desktop":"center","Mobile":"center"},"horizontalAlign":{"Desktop":"default","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"left":"10","top":"","bottom":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"hideMobile":true} -->
<!-- wp:gutenverse/icon {"elementId":"guten-Aplvqa","icon":"gtn gtn-play1-light","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0yNy40MDYgMTUuODEzbC0yMS45MDYtMTUuMDk0cS0wLjE1Ni0wLjEyNS0wLjM3NS0wLjE0MXQtMC40MDYgMC4wNzhxLTAuMTg4IDAuMTI1LTAuMjk3IDAuMjk3dC0wLjEwOSAwLjM5MXYzMC4xODhxMCAwLjIxOSAwLjEwOSAwLjM5MXQwLjI5NyAwLjI2NnEwLjA5NCAwLjA2MyAwLjE4OCAwLjA3OHQwLjE4OCAwLjAxNiAwLjIwMy0wLjAzMSAwLjIwMy0wLjA5NGwyMS45MDYtMTUuMDk0cTAuMTU2LTAuMTI1IDAuMjUtMC4yODF0MC4wOTQtMC4zNDRxLTAuMDMxLTAuMTg4LTAuMTA5LTAuMzU5dC0wLjIzNC0wLjI2NnoiPjwvcGF0aD4KPC9zdmc+Cg==","iconAlign":{"Mobile":"center"},"ariaLabel":"play video","iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"19","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"iconPadding":{"Desktop":"0","Mobile":"0"},"iconColorTwo":{"type":"variable","id":"primary"},"iconColorHoverOne":{"r":0,"g":0,"b":0,"a":0},"iconColorHoverTwo":{"type":"variable","id":"primary"},"iconShape":"circle","url":"#","animation":{"type":{"Desktop":"none"},"duration":"normal"},"background":{"type":"default","color":{"type":"variable","id":"third"}},"backgroundHover":{"type":"default","color":{"type":"variable","id":"secondary"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"15","top":"","right":"","bottom":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"20","top":"17","right":"16","bottom":"13"}},"Mobile":{"unit":"px","dimension":{"right":"17","left":"19","top":"12","bottom":"12"}}},"positioningType":{"Desktop":"inline","Mobile":"inline"},"positioningAlign":{"Desktop":"center","Mobile":"center"}} /-->

<!-- wp:gutenverse/button {"elementId":"guten-6Cdrmm","content":"Watch Video","url":"#","alignButton":{"Desktop":"right","Mobile":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":0,"g":0,"b":0,"a":0}},"buttonBackgroundHover":{"type":"default","color":""},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":"25"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"20"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal","delay":"40"},"color":{"type":"variable","id":"third"},"typography":{"type":"variable","id":"button1-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"12"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":"uppercase","weight":"500","transform":"uppercase"},"positioningType":{"Desktop":"inline","Tablet":"inline","Mobile":"inline"},"positioningAlign":{"Tablet":"center","Desktop":"center","Mobile":"center"},"ariaLabel":"watch video"} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
