<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse 404 Hero', 'accountra' ),
	'categories' => array( 'accountra-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"gap":"no","elementId":"guten-xqkBG7","background":{"type":"default","image":{"Desktop":{"id":28,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/work-architecture-sky-roof-building-city-1037258-pxhere.com_.webp"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"xposition":{"Desktop":{"point":"","unit":"px"}},"yposition":{"Desktop":{"point":"","unit":"px"}},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","color":{"r":0,"g":0,"b":0,"a":1},"gradientColor":[{"color":"rgba(27, 97, 243, 1)","active":false,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(16, 243, 240, 0.8)","active":true,"opacity":0.8,"id":2,"offset":"1.000"}],"gradientType":"linear","gradientAngle":90},"opacity":"0.8","margin":{"Desktop":{"unit":"px","dimension":{"top":"-130"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"270","bottom":"150","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"300","bottom":"120"}},"Mobile":{"unit":"px","dimension":{"top":"300","bottom":"80"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-CfBRbG"} -->
<!-- wp:gutenverse/heading {"elementId":"guten-Vxgvwr","content":"404","textAlign":{"Mobile":"center","Desktop":"center"},"color":{"type":"variable","id":"secondary"},"typography":{"font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"point":"156","unit":"px"},"Mobile":{"point":"110","unit":"px"}},"spacing":{"Desktop":""},"weight":"500","lineHeight":{"Desktop":{"unit":"em","point":"1.1"}}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"14","left":"0"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"none"},"duration":"slow"}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-Tkgmps","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"third"},"typography":{"type":"variable","id":"body-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":[]},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"right":"25","left":"25"}}}} -->
<!-- wp:paragraph {"align":"center"} -->
<p class="has-text-align-center">It looks like nothing was found at this location. Maybe try a search?</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"width":{"Desktop":"1140"},"isChild":true,"elementId":"guten-3N5hQw"} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-03ird5","horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"left":"","top":"","right":"","bottom":""}},"Tablet":{"unit":"px","dimension":{"left":"0"}}}} -->
<!-- wp:gutenverse/search {"elementId":"guten-F7QZDi","formStyle":{"Desktop":"fit-content","Mobile":"100%"},"buttonWidth":{"Desktop":{"point":"9","unit":"%"},"Mobile":{"unit":"%","point":"100"}},"placeholderColor":{"Desktop":{"type":"variable","id":"gv-color-text-placeholder"}},"inputPlaceholder":"Search...","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"15","left":"0"}}},"inputWidth":{"Desktop":{"unit":"%","point":"42"},"Tablet":{"unit":"%","point":"88"},"Mobile":{"unit":"%","point":"100"}},"inputTypography":{"type":"variable","id":"body-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"inputColorNormal":{"Desktop":{"type":"variable","id":"gv-color-text-primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"all":{"type":"solid","width":1,"color":{"r":37,"g":36,"b":37,"a":0.1}}},"inputColorHover":{"Desktop":{"type":"variable","id":"gv-color-text-primary"}},"inputBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-primary"}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"gv-color-text-primary"}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"all":{"width":1,"type":"solid","color":{"type":"variable","id":"gv-color-primary"}}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"gv-color-white"}},"alignContent":{"Desktop":"center"}} -->
<!-- wp:gutenverse/button {"elementId":"guten-tou0NN","role":"submit","content":"","buttonSize":"xs","buttonWidth":{"Desktop":"100"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"32","bottom":"20","left":"32"}}},"buttonBackground":{"color":{"type":"variable","id":"gv-color-primary"},"type":"default"},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-background-primary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}}},"showIcon":true,"icon":"fas fa-search","iconSize":{"Desktop":{"point":"15","unit":"px"}},"color":{"type":"variable","id":"gv-color-background-primary"},"iconColor":{"type":"variable","id":"gv-color-background-primary"},"typography":{"type":"variable","id":"button2-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":{"Desktop":"0.1"},"weight":"500","transform":"uppercase"},"hoverIconColor":{"type":"variable","id":"gv-color-white"},"hoverTextColor":{"type":"variable","id":"gv-color-white"}} /-->
<!-- /wp:gutenverse/search -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
