<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Search Section 1', 'accountra' ),
	'categories' => array( 'accountra-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"elementId":"guten-j83075","margin":{"Desktop":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"60"}}},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-a7atEM","horizontalAlign":{"Desktop":"center"}} -->
<!-- wp:gutenverse/search {"elementId":"guten-F7QZDi","formStyle":{"Desktop":"fit-content","Mobile":"100%"},"buttonWidth":{"Desktop":{"point":"9","unit":"%"},"Mobile":{"unit":"%","point":"100"}},"placeholderColor":{"Desktop":{"type":"variable","id":"gv-color-text-placeholder"}},"inputPlaceholder":"Search...","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"20","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"15","left":"0"}}},"inputWidth":{"Desktop":{"unit":"%","point":"89"},"Tablet":{"unit":"%","point":"88"},"Mobile":{"unit":"%","point":"100"}},"inputTypography":{"type":"variable","id":"body-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"inputColorNormal":{"Desktop":{"type":"variable","id":"gv-color-text-primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"all":{"type":"solid","width":1,"color":{"r":37,"g":36,"b":37,"a":0.1}}},"inputColorHover":{"Desktop":{"type":"variable","id":"gv-color-text-primary"}},"inputBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"all":{"type":"solid","width":1,"color":{"type":"variable","id":"gv-color-primary"}}},"inputColorFocus":{"Desktop":{"type":"variable","id":"gv-color-text-primary"}},"inputBorderFocus":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}},"all":{"width":1,"type":"solid","color":{"type":"variable","id":"gv-color-primary"}}},"alignContent":{"Desktop":"center"}} -->
<!-- wp:gutenverse/button {"elementId":"guten-tou0NN","role":"submit","content":"","buttonSize":"xs","buttonWidth":{"Desktop":"100"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"32","bottom":"20","left":"32"}}},"buttonBackground":{"color":{"type":"variable","id":"gv-color-primary"},"type":"default"},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-background-primary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"5","bottom":"5","left":"5"}}}},"showIcon":true,"icon":"fas fa-search","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTQxNiAyMDhjMCA0NS45LTE0LjkgODguMy00MCAxMjIuN0w1MDIuNiA0NTcuNGMxMi41IDEyLjUgMTIuNSAzMi44IDAgNDUuM3MtMzIuOCAxMi41LTQ1LjMgMEwzMzAuNyAzNzZjLTM0LjQgMjUuMi03Ni44IDQwLTEyMi43IDQwQzkzLjEgNDE2IDAgMzIyLjkgMCAyMDhTOTMuMSAwIDIwOCAwUzQxNiA5My4xIDQxNiAyMDh6TTIwOCAzNTJhMTQ0IDE0NCAwIDEgMCAwLTI4OCAxNDQgMTQ0IDAgMSAwIDAgMjg4eiIvPjwvc3ZnPg==","iconSize":{"Desktop":{"point":"15","unit":"px"}},"color":{"type":"variable","id":"gv-color-background-primary"},"iconColor":{"type":"variable","id":"gv-color-background-primary"},"typography":{"type":"variable","id":"button2-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"},"Tablet":{"unit":"px","point":"14"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":{"Desktop":"0.1"},"weight":"500","transform":"uppercase"},"hoverIconColor":{"type":"variable","id":"gv-color-white"},"hoverTextColor":{"type":"variable","id":"gv-color-white"}} /-->
<!-- /wp:gutenverse/search -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
