<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse About', 'accountra' ),
	'categories' => array( 'accountra-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":1140,"Tablet":""},"elementId":"guten-Ira8ak","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","right":"0","bottom":"100","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"80","right":"","bottom":"80","left":""}},"Mobile":{"unit":"px","dimension":{"top":"60","bottom":"60"}}}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100,"Mobile":null},"elementId":"guten-UWb9lp","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40"}},"Tablet":{"unit":"px","dimension":{"right":"30","left":"10"}},"Mobile":{"unit":"px","dimension":{"right":"15"}}}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-CZOP9H","content":"Welcome To Accountra","color":{"type":"variable","id":"secondary"},"typography":{"type":"variable","id":"h3-font-secondary","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Tablet":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"400","transform":"default"},"containsAnchorTag":false,"background":{"type":"default","color":""},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"10","top":"","right":"","left":""}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"0"}} /-->

<!-- wp:gutenverse/heading {"elementId":"guten-DZHhFF","content":"We Are Calculating The Best Opportunities For You","color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500","transform":"default"},"containsAnchorTag":false,"margin":{"Tablet":[],"Desktop":{"unit":"px","dimension":{"bottom":""}}},"padding":{"Tablet":{"unit":"px","dimension":{"right":"30"}},"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"80"}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-2UJA1S","textColor":{"type":"variable","id":"forth"},"typography":{"type":"variable","id":"body-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"160"}} -->
<!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat Duis aute irure dolor</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-ZmvTsx","margin":{"Desktop":{"unit":"px","dimension":{"top":"5"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"240"}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":52},"elementId":"guten-5Vyd0W","margin":{"Desktop":{"unit":"px","dimension":{"right":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":""}}}} -->
<!-- wp:gutenverse/icon-list {"elementId":"guten-ZRgAeu","spaceBetween":{"Desktop":"8"},"iconColor":{"type":"variable","id":"secondary"},"iconSize":{"Desktop":"13"},"textColor":{"type":"variable","id":"forth"},"textIndent":{"Desktop":"10"},"textTypography":{"type":"variable","id":"body-text-bold","font":{"label":"Heebo","value":"heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-m3ehtc","ariaLabel":"accountra about","iconType":"svg","text":"Learn from customer feedback"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-9jrGb1","ariaLabel":"accountra about","iconType":"svg","text":"Professional Team"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-HAwd7y","ariaLabel":"accountra about","iconType":"svg","text":"High Savings Potential"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-mIh7YQ","ariaLabel":"accountra about","iconType":"svg","text":"24/7 customer support"} /-->
<!-- /wp:gutenverse/icon-list -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":48,"Mobile":null},"elementId":"guten-NiruD0","margin":{"Mobile":{"unit":"px","dimension":{"top":"5","right":"0","bottom":"0","left":"0"}}},"padding":{"Mobile":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<!-- wp:gutenverse/icon-list {"elementId":"guten-LAJHYC","spaceBetween":{"Desktop":"8"},"iconColor":{"type":"variable","id":"secondary"},"iconSize":{"Desktop":"13"},"textColor":{"type":"variable","id":"forth"},"textIndent":{"Desktop":"10"},"textTypography":{"type":"variable","id":"body-text-bold","font":{"label":"Heebo","value":"heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"400"},"margin":{"Mobile":{"unit":"px","dimension":{"top":"0"}}},"padding":{"Mobile":[]}} -->
<!-- wp:gutenverse/icon-list-item {"elementId":"guten-INSaoq","ariaLabel":"accountra about","iconType":"svg","text":"High Savings Potenstial"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-ZtXSop","ariaLabel":"accountra about","iconType":"svg","text":"Learn from customer feedback"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-VzYUh5","ariaLabel":"accountra about","iconType":"svg","text":"24/7 customer support"} /-->

<!-- wp:gutenverse/icon-list-item {"elementId":"guten-XuoXdj","ariaLabel":"accountra about","iconType":"svg","text":"Professional Team"} /-->
<!-- /wp:gutenverse/icon-list -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-4O4mLG","margin":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"25"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":45,"Mobile":null},"elementId":"guten-trTdBS","verticalAlign":{"Desktop":"center"},"border":{"radius":{"Desktop":[],"Mobile":[]},"right":{"width":"1","color":{"r":240,"g":240,"b":240,"a":1},"type":"solid"}},"animation":{"type":{"Desktop":"fadeIn"},"duration":"slow"}} -->
<!-- wp:gutenverse/image {"elementId":"guten-WEIgrr","imgSrc":{"media":{"imageId":1269,"sizes":{"thumbnail":{"height":100,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/sign-image-updated.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/sign-image-updated.webp","height":100,"width":206,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"sign image","captionOriginal":"","width":{"Desktop":{"unit":"%","point":"45"}},"imgBorder":{"radius":{"Mobile":[],"Desktop":[]},"all":{"type":"none"}},"align":{"Desktop":"center","Mobile":"left"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"},"border":{"radius":{"Mobile":[],"Desktop":[]},"right":{"type":"none"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"imageLoad":"lazy"} /-->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":55,"Mobile":null},"elementId":"guten-F6ycAQ","verticalAlign":{"Desktop":"center"},"border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"","left":"50"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInRight"},"delay":"","duration":"normal"}} -->
<!-- wp:gutenverse/heading {"elementId":"guten-luBkDg","content":"Chad Gibbons","type":3,"color":{"type":"variable","id":"primary"},"typography":{"type":"variable","id":"h3-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"20"},"Tablet":{"unit":"px","point":"20"},"Mobile":{"unit":"px","point":"18"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500"},"containsAnchorTag":false,"margin":{"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} /-->

<!-- wp:gutenverse/text-editor {"elementId":"guten-uvEx5e","textColor":{"type":"variable","id":"forth"},"typography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"14","unit":"px"},"Mobile":{"point":"14","unit":"px"}},"weight":"300"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"-12","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:paragraph -->
<p>– Founder Accountra</p>
<!-- /wp:paragraph -->
<!-- /wp:gutenverse/text-editor -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":100},"elementId":"guten-CSphzF","background":{"type":"gradient"},"backgroundOverlay":{"type":"gradient","gradientType":"linear","gradientColor":[{"color":"rgba(234, 234, 234, 1)","active":false,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(221, 221, 221, 1)","active":false,"opacity":1,"id":3,"offset":"0.321"},{"color":"rgba(255, 255, 255, 1)","active":false,"opacity":1,"id":4,"offset":"0.323"},{"color":"rgba(255, 255, 255, 1)","active":true,"id":7,"offset":"0.701"},{"color":"rgba(221, 221, 221, 1)","active":false,"id":5,"offset":"0.702"},{"color":"rgba(221, 221, 221, 1)","active":false,"opacity":1,"id":2,"offset":"1.000"}],"gradientAngle":50},"opacity":"0.3","margin":{"Tablet":{"unit":"px","dimension":{"top":"30"}},"Desktop":[]},"padding":{"Tablet":[],"Desktop":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"0"}} -->
<!-- wp:gutenverse/image {"elementId":"guten-1OILTa","imgSrc":{"media":{"imageId":1149,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/architecture-sky-window-glass-building-city.webp","orientation":"landscape"},"medium":{"height":200,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/architecture-sky-window-glass-building-city.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/architecture-sky-window-glass-building-city.webp","height":587,"width":880,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"architecture sky window","captionOriginal":"","width":{"Desktop":{"unit":"%","point":"92"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[]}},"margin":{"Desktop":[],"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"25"}},"Tablet":[]},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/image {"elementId":"guten-TH6PEQ","imgSrc":{"media":{"imageId":1159,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/achievement-african-african-american-arms-raised-bangkok-black.webp","orientation":"landscape"},"medium":{"height":207,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/achievement-african-african-american-arms-raised-bangkok-black.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/achievement-african-african-american-arms-raised-bangkok-black.webp","height":551,"width":800,"orientation":"landscape"}}},"size":"full"},"altType":"original","altOriginal":"african american arms raised","captionOriginal":"","width":{"Desktop":{"unit":"%","point":"85"}},"imgBorder":{"radius":{"Desktop":[],"Tablet":[],"Mobile":[]},"all":{"type":"solid","width":"20","color":{"r":255,"g":255,"b":255,"a":1}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"50"},"border":{"radius":{"Mobile":[]},"all":{"width":""}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-230","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"%","dimension":{"top":""}},"Mobile":{"unit":"%","dimension":{"top":"-35"}}},"padding":{"Desktop":[],"Tablet":[],"Mobile":[]},"zIndex":{"Desktop":"2"},"imageLoad":"lazy"} /-->

<!-- wp:gutenverse/section {"isChild":true,"elementId":"guten-bs96P3","margin":{"Tablet":[]},"padding":{"Tablet":[]}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-HPfEoe","margin":{"Desktop":{"unit":"%","dimension":{"left":"45","right":"45","top":"","bottom":""}},"Tablet":{"unit":"%","dimension":{"right":"","left":""}},"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":[]},"Tablet":[],"Mobile":[]}} -->
<!-- wp:gutenverse/icon {"elementId":"guten-DMgolF","icon":"gtn gtn-play1-light","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiI+CjxwYXRoIGQ9Ik0yNy40MDYgMTUuODEzbC0yMS45MDYtMTUuMDk0cS0wLjE1Ni0wLjEyNS0wLjM3NS0wLjE0MXQtMC40MDYgMC4wNzhxLTAuMTg4IDAuMTI1LTAuMjk3IDAuMjk3dC0wLjEwOSAwLjM5MXYzMC4xODhxMCAwLjIxOSAwLjEwOSAwLjM5MXQwLjI5NyAwLjI2NnEwLjA5NCAwLjA2MyAwLjE4OCAwLjA3OHQwLjE4OCAwLjAxNiAwLjIwMy0wLjAzMSAwLjIwMy0wLjA5NGwyMS45MDYtMTUuMDk0cTAuMTU2LTAuMTI1IDAuMjUtMC4yODF0MC4wOTQtMC4zNDRxLTAuMDMxLTAuMTg4LTAuMTA5LTAuMzU5dC0wLjIzNC0wLjI2NnoiPjwvcGF0aD4KPC9zdmc+Cg==","iconAlign":{"Desktop":"center"},"ariaLabel":"play video","iconColorOne":{"r":0,"g":0,"b":0,"a":0},"iconSize":{"Desktop":{"point":"18","unit":"px"},"Mobile":{"point":"15","unit":"px"}},"iconPadding":{"Desktop":"0","Mobile":"12"},"iconColorTwo":{"type":"variable","id":"primary"},"iconShape":"circle","animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"80"},"background":{"type":"default","color":{"type":"variable","id":"secondary"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-530","right":"","bottom":"","left":""}},"Tablet":{"unit":"%","dimension":{"top":"-980","right":"20","bottom":"","left":"6"}},"Mobile":{"unit":"%","dimension":{"top":"-580","right":"5","left":"-10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"14","top":"15","bottom":"12","left":"17"}},"Tablet":{"unit":"px","dimension":{"top":"15","right":"","bottom":"13","left":""}},"Mobile":{"unit":"px","dimension":{"top":"6","right":"5","bottom":"5","left":"7"}}},"zIndex":{"Desktop":"3"},"positioningType":{"Desktop":"default"},"positioningAlign":{"Desktop":"center"}} /-->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
