<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Single Post Title', 'accountra' ),
	'categories' => array( 'accountra-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"890"},"elementId":"guten-49WXTt","background":{"type":"default","image":{"Desktop":{"id":433,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/analysis-brainstorming-business-businessman-businesswoman-collaboration-1455461-pxhere.com_.webp"}},"color":"","size":{"Desktop":"cover"},"position":{"Desktop":"center center"},"xposition":{"Desktop":{"point":"","unit":"px"}},"yposition":{"Desktop":{"point":"45","unit":"px"}},"width":{"Desktop":{"point":"126","unit":"px"}}},"backgroundOverlay":{"type":"default","color":{"r":26,"g":20,"b":20,"a":1},"gradientColor":[{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":1,"offset":"0.000"},{"color":"rgba(255, 255, 255, 0)","active":false,"opacity":0,"id":3,"offset":"0.000"},{"color":"rgba(255, 255, 255, 0)","id":7,"offset":"0.107","active":false},{"color":"rgba(255, 255, 255, 0)","active":true,"id":6,"offset":"0.190"},{"color":"rgba(255, 255, 255, 0)","active":false,"id":5,"offset":"0.293"},{"color":"rgba(255, 255, 255, 0)","active":false,"id":4,"offset":"0.937"}],"gradientType":"linear","gradientAngle":270,"image":{"Desktop":[]}},"opacity":"0.8","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-180","right":"","bottom":"","left":""}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"280","bottom":"150"}},"Tablet":{"unit":"px","dimension":{"top":"340","bottom":"120","right":"10","left":"10"}}},"zIndex":{"Desktop":"1"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-4YvS4T","horizontalAlign":{"Desktop":"center"},"margin":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":[]},"padding":{"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Desktop":[]}} -->
<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-b2yj97","margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"none"},"duration":"normal"},"wrapColumn":{"Desktop":false,"Tablet":false,"Mobile":true}} -->
<!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null},"elementId":"guten-HnInik","horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<!-- wp:gutenverse/post-title {"elementId":"guten-Jrdxu0","alignment":{"Tablet":"center","Desktop":"center"},"typography":{"type":"variable","id":"h2-font","font":{"label":"Poppins","value":"Poppins","type":"google"},"size":{"Desktop":{"unit":"px","point":"32"},"Tablet":{"unit":"px","point":"32"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"500","transform":"default"},"color":{"type":"variable","id":"third"},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"30"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"right":"30","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}}} -->
<div class="guten-element guten-post-title guten-Jrdxu0"></div>
<!-- /wp:gutenverse/post-title -->

<!-- wp:gutenverse/icon {"elementId":"guten-KEWpT8","icon":"far fa-user-circle","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1MTIgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTQwNi41IDM5OS42QzM4Ny40IDM1Mi45IDM0MS41IDMyMCAyODggMzIwSDIyNGMtNTMuNSAwLTk5LjQgMzIuOS0xMTguNSA3OS42QzY5LjkgMzYyLjIgNDggMzExLjcgNDggMjU2QzQ4IDE0MS4xIDE0MS4xIDQ4IDI1NiA0OHMyMDggOTMuMSAyMDggMjA4YzAgNTUuNy0yMS45IDEwNi4yLTU3LjUgMTQzLjZ6bS00MC4xIDMyLjdDMzM0LjQgNDUyLjQgMjk2LjYgNDY0IDI1NiA0NjRzLTc4LjQtMTEuNi0xMTAuNS0zMS43YzcuMy0zNi43IDM5LjctNjQuMyA3OC41LTY0LjNoNjRjMzguOCAwIDcxLjIgMjcuNiA3OC41IDY0LjN6TTI1NiA1MTJBMjU2IDI1NiAwIDEgMCAyNTYgMGEyNTYgMjU2IDAgMSAwIDAgNTEyem0wLTI3MmE0MCA0MCAwIDEgMSAwLTgwIDQwIDQwIDAgMSAxIDAgODB6bS04OC00MGE4OCA4OCAwIDEgMCAxNzYgMCA4OCA4OCAwIDEgMCAtMTc2IDB6Ii8+PC9zdmc+","iconColorOne":{"r":249,"g":37,"b":37,"a":0},"iconSize":{"Desktop":{"point":"17","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"secondary"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10"}},"Mobile":{"unit":"px","dimension":{"left":""}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"left":""}}},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} /-->

<!-- wp:gutenverse/post-author {"elementId":"guten-aikaj4","typography":{"type":"variable","id":"body-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"color":{"type":"variable","id":"third"},"authorBorder":{"radius":{"Desktop":[]}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"30"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"10","bottom":"","left":""}}},"padding":{"Desktop":[],"Mobile":[]},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
<div class="guten-element guten-post-author guten-aikaj4"></div>
<!-- /wp:gutenverse/post-author -->

<!-- wp:gutenverse/icon {"elementId":"guten-4g4hoD","icon":"far fa-calendar-alt","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA0NDggNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTE1MiAyNGMwLTEzLjMtMTAuNy0yNC0yNC0yNHMtMjQgMTAuNy0yNCAyNFY2NEg2NEMyOC43IDY0IDAgOTIuNyAwIDEyOHYxNiA0OFY0NDhjMCAzNS4zIDI4LjcgNjQgNjQgNjRIMzg0YzM1LjMgMCA2NC0yOC43IDY0LTY0VjE5MiAxNDQgMTI4YzAtMzUuMy0yOC43LTY0LTY0LTY0SDM0NFYyNGMwLTEzLjMtMTAuNy0yNC0yNC0yNHMtMjQgMTAuNy0yNCAyNFY2NEgxNTJWMjR6TTQ4IDE5Mmg4MHY1Nkg0OFYxOTJ6bTAgMTA0aDgwdjY0SDQ4VjI5NnptMTI4IDBoOTZ2NjRIMTc2VjI5NnptMTQ0IDBoODB2NjRIMzIwVjI5NnptODAtNDhIMzIwVjE5Mmg4MHY1NnptMCAxNjB2NDBjMCA4LjgtNy4yIDE2LTE2IDE2SDMyMFY0MDhoODB6bS0xMjggMHY1NkgxNzZWNDA4aDk2em0tMTQ0IDB2NTZINjRjLTguOCAwLTE2LTcuMi0xNi0xNlY0MDhoODB6TTI3MiAyNDhIMTc2VjE5Mmg5NnY1NnoiLz48L3N2Zz4=","iconColorOne":{"r":249,"g":37,"b":37,"a":0},"iconSize":{"Desktop":{"point":"17","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"secondary"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} /-->

<!-- wp:gutenverse/post-date {"elementId":"guten-ce3oi6","typography":{"type":"variable","id":"body-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"color":{"type":"variable","id":"third"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0","right":"30"}},"Mobile":{"unit":"px","dimension":{"right":"10"}}},"padding":{"Desktop":[],"Mobile":[]},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
<div class="guten-element guten-post-date guten-ce3oi6"></div>
<!-- /wp:gutenverse/post-date -->

<!-- wp:gutenverse/icon {"elementId":"guten-Fh2n8K","icon":"far fa-folder-open","iconType":"svg","iconSVG":"PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA1NzYgNTEyIj48IS0tISBGb250IEF3ZXNvbWUgRnJlZSA2LjUuMSBieSBAZm9udGF3ZXNvbWUgLSBodHRwczovL2ZvbnRhd2Vzb21lLmNvbSBMaWNlbnNlIC0gaHR0cHM6Ly9mb250YXdlc29tZS5jb20vbGljZW5zZS9mcmVlIChJY29uczogQ0MgQlkgNC4wLCBGb250czogU0lMIE9GTCAxLjEsIENvZGU6IE1JVCBMaWNlbnNlKSBDb3B5cmlnaHQgMjAyMyBGb250aWNvbnMsIEluYy4gLS0+PHBhdGggZD0iTTM4NCA0ODBoNDhjMTEuNCAwIDIxLjktNiAyNy42LTE1LjlsMTEyLTE5MmM1LjgtOS45IDUuOC0yMi4xIC4xLTMyLjFTNTU1LjUgMjI0IDU0NCAyMjRIMTQ0Yy0xMS40IDAtMjEuOSA2LTI3LjYgMTUuOUw0OCAzNTcuMVY5NmMwLTguOCA3LjItMTYgMTYtMTZIMTgxLjVjNC4yIDAgOC4zIDEuNyAxMS4zIDQuN2wyNi41IDI2LjVjMjEgMjEgNDkuNSAzMi44IDc5LjIgMzIuOEg0MTZjOC44IDAgMTYgNy4yIDE2IDE2djMyaDQ4VjE2MGMwLTM1LjMtMjguNy02NC02NC02NEgyOTguNWMtMTcgMC0zMy4zLTYuNy00NS4zLTE4LjdMMjI2LjcgNTAuN2MtMTItMTItMjguMy0xOC43LTQ1LjMtMTguN0g2NEMyOC43IDMyIDAgNjAuNyAwIDk2VjQxNmMwIDM1LjMgMjguNyA2NCA2NCA2NEg4Ny43IDM4NHoiLz48L3N2Zz4=","iconColorOne":{"r":249,"g":37,"b":37,"a":0},"iconSize":{"Desktop":{"point":"17","unit":"px"}},"iconPadding":{"Desktop":"0"},"iconColorTwo":{"type":"variable","id":"secondary"},"margin":{"Desktop":{"unit":"px","dimension":{"right":"10"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} /-->

<!-- wp:gutenverse/post-terms {"elementId":"guten-V1kRnx","typography":{"type":"variable","id":"body-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Tablet":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"color":{"type":"variable","id":"third"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","bottom":"0"}}},"padding":{"Desktop":[]},"positioningType":{"Desktop":"inline"},"positioningAlign":{"Desktop":"center"}} -->
<div class="guten-element guten-post-terms guten-V1kRnx"></div>
<!-- /wp:gutenverse/post-terms -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->
<!-- /wp:gutenverse/column -->
<!-- /wp:gutenverse/section -->',
	'is_sync' => false,
);
